version: '3.6'

services:
  leap-consent-ui:
    image: leap-consent-ui
    container_name: leap-consent-ui
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SLS-HOST-URL: ${SLS-HOST-URL}
      HAPI-FHIR-URL: ${HAPI-FHIR-URL}
      SH-API-URL: ${SH-API-URL}
    ports:
      - 8080:8080
