sh:
  url: ${SH_API_URL:https://stronghold-ui-api-jmiahzqi2a-uw.a.run.app}

sls:
  url: ${SLS_HOST_URL:http://sdhc-sls-leap.uc.r.appspot.com}

hapi-fhir:
  url: ${HAPI_FHIR_URL:https://sdhc-hapi-fhir-leap-wafxyq4bza-uc.a.run.app/fhir/}

datasource:
  url: jdbc:postgresql://${DB_NAME:localhost:5432/leap_consent?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&jdbcCompliantTruncation=false&createDatabaseIfNotExist=true}
  username: ${DB_USER:postgres}
  password: ${DB_PASS:saperi}


